FROM resystit/bind9

COPY common /etc/bind/common
COPY bind_delegated_subzone/zones/ /var/bind/
COPY bind_delegated_subzone/named.conf /etc/bind/named.conf

RUN named-checkconf \
  && named-checkzone earth.sun.galaxy /var/bind/earth.sun.galaxy.zone