FROM resystit/bind9

COPY common /etc/bind/common
COPY bind_views/zones/ /var/bind/
COPY bind_views/named.conf /etc/bind/named.conf

RUN named-checkconf \
  && named-checkzone sun.galaxy /var/bind/external.sun.galaxy.zone \
  && named-checkzone sun.galaxy /var/bind/internal.sun.galaxy.zone
  